"""add reminder_hour and reminder_minute to users

Revision ID: 37132b14b933
Revises: 69df4986f8e4
Create Date: 2026-05-27 11:42:38.390917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '37132b14b933'
down_revision: Union[str, None] = '69df4986f8e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reminder_hour', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('reminder_minute', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('reminder_minute')
        batch_op.drop_column('reminder_hour')

    # ### end Alembic commands ###
