"""add affiliate_code to users

Revision ID: 69df4986f8e4
Revises: 0001
Create Date: 2026-05-26 18:15:16.191736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '69df4986f8e4'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('affiliate_code', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('affiliate_code')

    # ### end Alembic commands ###
